// questions.js
// Array of {question, answer} - Karma zorlukta sorular
const QUESTIONS = [
  { q: "İslam'da Allah'ın birliği inancı hangi terimle ifade edilir?", a: "Tevhid" },
  { q: "Allah’a olan bağlılığı ifade eden, O’nun rızasını kazanmak amacıyla yapılan bilinçli davranışlardır.", a: "İbadet" },
  { q: "Yapılan ibadeti sadece Allah rızası için yapmak, gösterişten uzak durmaktır.", a: "İhlas" },
  { q: "Allah’ı görüyormuşçasına ibadet etmek; her an Allah’ın gözetimi altında olunduğunun bilincinde olmaktır.", a: "İhsan" },
  { q: "Ölçülü, dengeli ve aşırılıktan uzak bir yaşam tarzını benimsemektir. İslam’da her konuda orta yol tavsiye edilir.", a: "İtidal" },
  { q: "Kuran-ı Kerim kaç sureden oluşmaktadır?", a: "114" },
  { q: "Kuran-ı Kerim'in ilk suresi nedir?(Yalnızca ismi)", a: "Fatiha" },
  { q: "Kur'an-ı Kerim'in son suresi nedir?(Yalnızca ismi)", a: "Nas" },
  { q: "Sabah Namazı kaç rekattır?(sayı ile)", a: "4" },
  { q: "İmanın Şartları kaç tanedir?", a: "6" },
  { q: "İslamın şartları kaç tanedir?", a: "5" },
  { q: "Kadir Gecesi hangi ayda bulunur?", a: "Ramazan" },
  { q: "Hz. Musa'ya verilen kutsal kitap hangisidir?", a: "Tevrat" },
  { q: "Hz. İsa'ya verilen kutsal kitap hangisidir?", a: "İncil" },
  { q: "Hz. Davud'a verilen kutsal kitap hangisidir?", a: "Zebur" },
  { q: "Vahiy iletmek ile görevli melek hangisidir?", a: "Cebrail" },
  { q: "Sûra üflemek ile görevli melek hangisidir?", a: "İsrafil" },
  { q: "Can almak ile görevli melek hangisidir?", a: "Azrail" },
  { q: "Doğa olaylarını idare etmekle görecli melek hangisidir?", a: "Mikail" },
  { q: "Peygamberlerin doğruluğunu ifade eden sıfat nedir?", a: "Sıdk" },
  { q: "Peygamberlerin zeki ve akıllı olmasını ifade eden sıfat nedir?", a: "Fetanet" },
  { q: "Peygamberlerin güvenilirlik sıfatı nedir?", a: "Emanet" },
  { q: "Hicri takvimin başlangıcı hangi olaydır?", a: "Hicret" },
  { q: "Hz. Muhammed'in vefat ettiği yıl kaçtır?", a: "632" },
  { q: "Kur'an-ı Kerim'in en uzun suresi nedir?", a: "Bakara" },
];
