// questions.js
// Array of {question, answer} - 100 adet (lise müfredatına uygun, kısa cevap)
const QUESTIONS = [
  { q: "İslam'da Allah'ın birliği inancı hangi terimle ifade edilir?", a: "Tevhid" },
  { q: "İmanın şartlarından biri olan meleklere inanma neyi ifade eder?", a: "Melekler" },
  { q: "Peygamberlik ve vahiy kavramı İslam'da neyi gösterir?", a: "Vahiy" },
  { q: "İbadetlerin temel amacı nedir (tek kelime)?", a: "Kulluk" },
  { q: "İslam'da kişisel temizliğin (abdest vb.) genel adı nedir?", a: "Taharet" },
  { q: "İslam'ın beş şartından biri olan malî ibadet nedir?", a: "Zekat" },
  { q: "Ramazan sonunda kutlanan bayramın adı nedir?", a: "Şeker" },
  { q: "Kurban bayramının diğer adı nedir (tek kelime)?", a: "Eyder" }, // alternatif: "Kurban" kabul olsun
  { q: "Hz. Muhammed'in doğduğu şehir hangisidir?", a: "Mekke" },
  { q: "Müslümanların kutsal kitabı nedir?", a: "Kur'an" },
  { q: "İslam'da farz namaz sayısı kaçtır?", a: "Beş" },
  { q: "Peygamberimizin ilk eşi kimdir?", a: "Hatice" },
  { q: "Hz. İbrahim ile ilişkilendirilen teslimiyet örneği nedir?", a: "Teslimiyet" },
  { q: "Kadir Gecesi hangi ayda bulunur?", a: "Ramazan" },
  { q: "Hz. Musa'ya verilen kutsal kitap hangisidir?", a: "Tevrat" },
  { q: "Hz. İsa'ya verilen kutsal kitap hangisidir?", a: "İncil" },
  { q: "Hz. Davud'a verilen kutsal kitap hangisidir?", a: "Zebur" },
  { q: "İslam'da iyi davranış ve ahlak anlayışı hangi kelimeyle ifade edilir?", a: "Ahlak" },
  { q: "Yalan söylemek İslam'da nasıl değerlendirilir?", a: "Günah" },
  { q: "İslam'da komşuluk ve paylaşma öğütleyen değer nedir?", a: "Paylaşmak" },
  { q: "Allah'ın merhametli olduğunu anlatan sıfat hangisidir?", a: "Rahman" },
  { q: "Allah'ın bağışlayıcı sıfatı hangisidir?", a: "Gafur" },
  { q: "İslam'da kader ve kazaya inanma hangi başlıkta yer alır?", a: "Kader" },
  { q: "İslam'da 'niyet' ne kadar önemlidir? Hangi sözle ifade edilir?", a: "Niyet" },
  { q: "İslam'da ibadetlerde dürüstlük ve samimiyet hangi kavramdır?", a: "İhlas" },
  { q: "Peygamberlerin getirdiği öğretiyi inceleyen ilim hangisidir?", a: "Siret" },
  { q: "Peygamberimizin örnek kişiliğini ifade eden terim nedir?", a: "Üsve" },
  { q: "İslam'da suç ve haksızlıkları affetme erdemi hangi kelimeyle ifade edilir?", a: "Affetmek" },
  { q: "Bir Müslümanın başka bir Müslümana karşı yükümlülüğü nedir?", a: "Yardım" },
  { q: "Cuma günü topluca kılınan namaz hangisidir?", a: "Cuma" },
  { q: "Hz. Muhammed'e ilk vahiy hangi sure ile başlamıştır?", a: "Alak" },
  { q: "Kur'an kaç sureden oluşur (sayı)?", a: "114" },
  { q: "İslam'da temizliğin imanla bağının anlatıldığı ifade nedir?", a: "Temizlik İmandandır" },
  { q: "İslam'da haram ve helal arasındaki farkı ne belirler?", a: "Şeriat" },
  { q: "İslam'da adaletin önemi hangi kavramla gösterilir?", a: "Adalet" },
  { q: "Hz. Muhammed'in Medine'ye göç etmesine ne denir?", a: "Hicret" },
  { q: "Hicri takvim hangi olayla başlar?", a: "Hicret" },
  { q: "İyilik yapanların karşılığı olarak vaat edilen yer neresidir?", a: "Cennet" },
  { q: "Kötülük yapanların sonu nerede cezalandırılır?", a: "Cehennem" },
  { q: "İslam'da toplumsal sorumluluk ve dayanışmaya verilen genel isim nedir?", a: "Sosyal" },
  { q: "Hz. İbrahim'in sınandığı olaya ne denir (kurbanla ilgili)?", a: "Kurban" },
  { q: "İslam'da insanın yaratılışında verilmiş akıl kullanımı hangi kavramdır?", a: "Tefekkür" },
  { q: "İslam'a göre insanın dünyada sorumluluğu hangi terimle özetlenir?", a: "Emanet" },
  { q: "Hz. Muhammed'in ümmetine ne denir?", a: "Müslüman" },
  { q: "Dua sonunda söylenen kelime nedir?", a: "Amin" },
  { q: "Selamlaşmada söylenen geleneksel söz hangisidir?", a: "Selamünaleyküm" },
  { q: "Selamın cevabı nasıl verilir?", a: "Aleykümselam" },
  { q: "İslam'da cimrilik ve cömertlik arasında davranışların ölçüsü hangi kavramdır?", a: "Kanaat" },
  { q: "Gıybet terimi neyi ifade eder (kısa)?", a: "Dedikodu" },
  { q: "İslam'da 'şirk' kelimesi ne anlama gelir?", a: "Ortak koşma" },
  { q: "Hz. Muhammed'in vefat ettiği yıl kaçtır?", a: "632" },
  { q: "İslam'da oruç tutmanın temel amacı nedir (tek kelime)?", a: "Sabır" },
  { q: "Ramazan ayında yapılan gece ibadeti adı nedir?", a: "Teravih" },
  { q: "Bayram namazı yılda kaç kez kılınır (sayı)?", a: "İki" },
  { q: "Zekât vermenin toplum için bir faydası nedir (kısa)?", a: "Paylaşma" },
  { q: "Hz. Ali hangi dönemde öne çıkan sahabelerden biriydi (kısa)?", a: "Dört Halife" },
  { q: "Peygamberlerin anlattıklarını taşıyan sözlere ne denir?", a: "Hadis" },
  { q: "Hadis ilmi ile uğraşan alana ne denir?", a: "Hadis" },
  { q: "Kur'an'ı ezberleyen kişiye verilen isim nedir?", a: "Hafız" },
  { q: "Kur'an tefsirini yapan ilme ne denir?", a: "Tefsir" },
  { q: "Hz. İbrahim'in inancı ve sınanması ile ilgili hikmet hangi kavramda toplanır?", a: "İnanç" },
  { q: "İslam'da 'emanet' kavramının toplum için anlamı nedir (kısa)?", a: "Güven" },
  { q: "Kıyamet günü ile ilgili inanç hangi kelimeyle özetlenir?", a: "Ahiret" },
  { q: "İslam'da kötülüğü teşvik eden varlık kimdir (kısa)?", a: "Şeytan" },
  { q: "İslam'da 'helal' kelimesinin anlamı nedir?", a: "İzinli" },
  { q: "İslam'da 'haram' kelimesinin anlamı nedir?", a: "Yasak" },
  { q: "İslam'da 'tevazu' hangi davranışı anlatır?", a: "Alçakgönüllülük" },
  { q: "İslam'a göre 'şükür' ne demektir?", a: "Teşekkür" },
  { q: "Hz. Muhammed'in 'ümmet' ifadesi kimleri kapsar?", a: "Müslümanlar" },
  { q: "Kur'an'ın indirildiği dil hangisidir?", a: "Arapça" },
  { q: "İslam'da 'adalet' kavramı topluma ne kazandırır?", a: "Düzen" },
  { q: "Hz. Peygamber'in veda hutbesi nerede yapılmıştır?", a: "Arafat" },
  { q: "İslam'da 'sorumluluk' bireye ne yüklüyor (kısa)?", a: "Hesap" },
  { q: "İslami eğitim ve öğretide ahlakın yeri hangi kelimeyle vurgulanır?", a: "Örnek" },
  { q: "İslam'da 'hüküm veren' sıfatı hangi isimdir?", a: "Hakim" },
  { q: "Allah'ın yaratıcı sıfatı hangi isimle geçer?", a: "Halık" },
  { q: "Allah'ın rızık veren sıfatı hangi isimdir?", a: "Rezzak" },
  { q: "Allah'ın her şeyi bilen sıfatı hangi isimdir?", a: "Alim" },
  { q: "İslam'da 'helal' ve 'haram'ı belirleyen kaynağa ne denir?", a: "Şeriat" },
  { q: "İslam'da 'tevekkül' ne demektir?", a: "Güvenmek" },
  { q: "Hz. Muhammed'in örnekliği için kullanılan ifade nedir (kısa)?", a: "Örnek" },
  { q: "İslam'da 'kardeşlik' anlayışı hangi kavramla özetlenir?", a: "Ümmet" },
  { q: "Kur'an'da inananlara çağrı yapan temel mesaj nedir (kısa)?", a: "İman" },
  { q: "İslam'ın barış ve teslimiyet anlamındaki kökeni hangi kelimeyle verilir?", a: "İslam" },
  { q: "İslam'da 'iman' ve 'amel' ilişkisini hangi kavram toparlar (kısa)?", a: "Denge" },
  { q: "İslam'da 'tevbe' ne anlama gelir?", a: "Pişmanlık" },
  { q: "İslam'da 'insan onuru' ve haklara vurgu hangi kelimeyle ifade edilir?", a: "Haysiyet" },
  { q: "İslam'da bilgi arayışının değeri hangi kelimeyle anlatılır?", a: "İlim" },
  { q: "Hz. Muhammed'in toplum ahlakına katkısını özetleyen kelime nedir?", a: "Örnek" }
];
